### ISSUE TITLE
rever.xsh does not upload .tar.gz to PyPI

### ISSUE THREAD

**Issue by saraedum** [echemdb/svgdigitizer#123]
While rever.xsh says that sdist should be run, it does not seem to work and only a wheel is uploaded to PyPI.

**Comment by saraedum** [comment]
(I manually uploaded tarballs to PyPI for the time being.)

**Comment by saraedum** [comment]
see https://github.com/regro/rever/issues/254 for the upstream issue.

**Comment by DunklesArchipel** [comment]
@saraedum I assume this can be closes?
