### ISSUE TITLE
Custom labels do not work in svgplot

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#124]
It is possible to use custom labels in `svgplot` such as `xlabel` = `V`. Bit then in the SVG file, the axis labels should also contain `V1` and `V2`.

In the example below the error appears once `df` is called. 
```python
from svgdigitizer.svg import SVG
from svgdigitizer.svgplot import SVGPlot

plot = SVGPlot(SVG(open('./svgdigitizer/doc/files/others/example_plot_p0_demo.svg', 'r')), sampling_interval=0.01, xlabel='U', ylabel='v')
plot.df.head()
```

I haven't had the chance to do a complete survey, where the error comes from and/or how it might be fixed.

- [ ] provide Example files in new PR

**Comment by DunklesArchipel** [comment]
Check if it woks when the labels in the svg file are names U1, U2, v1, and v2

**Comment by linuxrider** [comment]
This is somehow related to #135 as it influences the axis orientation?
