### ISSUE TITLE
Publish on conda-forge

### ISSUE THREAD

**Issue by saraedum** [echemdb/svgdigitizer#130]
We should publish svgdigitizer on conda-forge:

* Create a recipe with https://www.marcelotrevisani.com/grayskull
* Propose it in a PR, see https://github.com/conda-forge/staged-recipes#getting-started.

- [x]  See https://github.com/conda-forge/staged-recipes/pull/17931

**Comment by saraedum** [comment]
@DunklesArchipel @linuxrider could either of you do this? I can then review the PR.

**Comment by DunklesArchipel** [comment]
I added us as assignee.

**Comment by DunklesArchipel** [comment]
@saraedum @linuxrider @nicohoermann 
If you want to be listed as a maintainer of the `svgdigitizer` on conda-forge, then please leave a message in the following PR that you consent to be listed as maintainer.
https://github.com/conda-forge/staged-recipes/pull/17931

I have no clue how this works, but it seems that this is the last step. :)
