### ISSUE TITLE
Bug: Auto-detect axis orientation

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#149]
With the new implementations, some of the files on echemdb/website can not be converted anymore, since the axis are not detected properly ([Examples](https://github.com/echemdb/website/tree/main/literature/mello_2018_bromide_18562)).

Here are two files, containing an identical dataset. Some of the axes' labels are placed in different positions.
[bugged.svg](https://user-images.githubusercontent.com/39313137/160552093-957ae119-eb96-4661-a210-84733af5d45f.svg)
[working.svg](https://user-images.githubusercontent.com/39313137/160552096-c4df669e-5065-422f-86ac-3c50c948b0ae.svg)

If you use the current version of svgdigitizer the following different errors appear.
* working: `svgdigitizer cv working.svg`
```python
    current = 1 * CV.get_axis_unit(self.svgplot.axis_labels["y"])
KeyError: 'y'
```
This bug is fixed in #145 

* bugged: `svgdigitizer cv bugged.svg`
```python
 raise UnitConversionError(
astropy.units.core.UnitConversionError: 'uA / cm2' (electrical current density) and 'V' (electrical potential) are not convertible
(echemdb)
```
This is an indication that the x-axis was inferred from j1 and j2 (placed on the y-axis in the SVG)

If you use the new implementation of #145 the conversion works since it does not care whether x is in V or y is in V. Here we observe that the axes were wrongly extracted from the bugged version. In this case, sampling does not work, since digitize_cv tries to sample j.
```json
		"fields": [
			{
				"name": "j",
				"unit": "uA / cm2",
				"orientation": "x"
			},
			{
				"name": "E",
				"unit": "V",
				"orientation": "y",
				"reference": "RHE"
			}
```
in the working version this seems to be fine:
```json
		"fields": [
			{
				"name": "E",
				"unit": "V",
				"orientation": "x",
				"reference": "RHE"
			},
			{
				"name": "j",
				"unit": "uA / cm2",
				"orientation": "y"
			}
```

Comparing the content of the SVG in plain text, I cannot find any differences. Considering that I somehow managed to create a working version, I assume that it has something to to with the positioning of the axis labels or the lines connected to these labels. These are slightly different between both versions (compare position of j labels and the angle of the lines with respect to the plot).

**Comment by DunklesArchipel** [comment]
It can be ruled out that the order of the groups in the file has an influence.

**Comment by DunklesArchipel** [comment]
Output from svgplot.marked_points and axis_orientations for bugged.svg

```python
$ svgdigitizer cv bugged.svg
{'E1': ((906.00013, 1616.4919), 0.1, 'V vs. RHE'), 'E2': ((1883.3202, 1614.6666), 0.9, 'V vs. RHE'), 'j1': ((782.5011, 1546.586), -250.0, 'uA / cm2'), 'j2': ((786.12215, 790.02673), 300.0, 'uA / cm2')}
[[ 8.18572314e-04  3.91785733e-06 -6.47959808e-01]
 [-1.35775388e-03 -7.26981928e-01  8.75402515e+02]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]] E j
[[-0.51631263  0.85640018]
 [ 0.85640018  0.51631263]]
[[-1.35775388e-03 -7.26981928e-01  8.75402515e+02]
 [ 8.18572314e-04  3.91785733e-06 -6.47959808e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]] j E
[[-0.85640018  0.51631263]
 [ 0.51631263  0.85640018]]
```

**Comment by saraedum** [comment]
Part of this is a conceptual problem. Before determining the amount of rotation necessary, we turn both axes into SI units. In the above example, one axis is already in V while the other gets converted to A/m². So any small imprecision on that axis is multiplied by a factor 100. As a result the image in SI unit is actually somewhat skewed.

**Comment by saraedum** [comment]
If that's the only problem, then the following change should fix this:
```diff
diff --git a/svgdigitizer/svgplot.py b/svgdigitizer/svgplot.py
index da34b8f..d50e1ed 100644
--- a/svgdigitizer/svgplot.py
+++ b/svgdigitizer/svgplot.py
@@ -347,10 +347,10 @@ class SVGPlot:
             from numpy.linalg import qr

             A = self._transformation(
-                self.marked_points[f"{horizontal}1"],
-                self.marked_points[f"{horizontal}2"],
-                self.marked_points[f"{vertical}1"],
-                self.marked_points[f"{vertical}2"],
+                (self.marked_points[f"{horizontal}1"][0], 0),
+                (self.marked_points[f"{horizontal}2"][0], 1),
+                (self.marked_points[f"{vertical}1"][0], 0),
+                (self.marked_points[f"{vertical}2"][0], 1),
                 # We use marked aligned here to get a rotational portion in the
                 # transformation even if the user asked for axis-aligned for
                 # the eventual transformation.
```

But I doubt it actually.

**Comment by DunklesArchipel** [comment]
> Part of this is a conceptual problem. Before determining the amount of rotation necessary, we turn both axes into SI units. In the above example, one axis is already in V while the other gets converted to A/m². So any small imprecision on that axis is multiplied by a factor 100. As a result the image in SI unit is actually somewhat skewed.

I am not sure what you mean, but the conversion to SI units only happens in the CV module. Did you mean instead that the SVG unit scale (points) is converted into the values given in the plot on the respective axis?

**Comment by DunklesArchipel** [comment]
The approach you suggest actually works. I don't understand what you mean by not using 0 and 1.
