### ISSUE TITLE
Create more generic tests.

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#15]
I recommend creating more generic svg and yaml files for the tests which are not based on real examples. 
These should comprise different plot types, i.e., regular x-y plots, plots with scale bars, waterfall plots, ...

The files could be named:
* xy.svg
* xy_scalebar.svg
* xy_waterfall.svg
* xy_scalingfactor.svg

Tests should be run on all possibilities.

**Comment by saraedum** [comment]
:+1: these don't even have to be actual files but we could also use doctests to check that the most trivial things here get parsed correctly.

**Comment by DunklesArchipel** [comment]
> I believe that our doctesting now covers much of this and we also added some tests for `svgdigitizer digitize`. I believe that this can be closed now @DunklesArchipel .

Should we maybe create an issue with a task list where we still want to implement Doctests? @saraedum

**Comment by saraedum** [comment]
> > I believe that our doctesting now covers much of this and we also added some tests for `svgdigitizer digitize`. I believe that this can be closed now @DunklesArchipel .
> 
> Should we maybe create an issue with a task list where we still want to implement Doctests? @saraedum

I think we basically want doctests everywhere (in particular we want documentation everywhere.) I'll create an issue.

**Comment by saraedum** [comment]
This is now #73.
