### ISSUE TITLE
New version of click (8.1.0) is not compatible.

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#152]
I had to fix the version number of click to 8.0.3, since 8.1.0 is responsible for the failed doctests in the previous test runs.

_Originally posted by @DunklesArchipel in https://github.com/echemdb/svgdigitizer/issues/145#issuecomment-1083049922_

**Comment by saraedum** [comment]
This is a problem in frictionless. `get_terminal_size` had apparently been marked as deprecated for a while.
