### ISSUE TITLE
Issue extracting the curve from svg when the objects are not placed in the correct layer.

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#16]
It seems that digitization of the path in the svg is only possible when the objects are located in specific layers.

In some cases, I did not receive a plot or csv file of the curve, but instead, the two points of a line connecting the axis and the text field were plotted. 

I finally managed to get the correct plot and csv file when all objects were be located in one layer:
![image](https://user-images.githubusercontent.com/39313137/125166137-7d664680-e19a-11eb-9dc4-c7604db03bf8.png)

Spontaneously I was not able to reproduce the issue. My Inkscape crashed and I lost that error state. I will update this issue, once it appears again.

**Comment by DunklesArchipel** [comment]
This caused the bug.
![image](https://user-images.githubusercontent.com/39313137/125178219-086b2f00-e1e3-11eb-8116-5b4a2d530ad2.png)

**Comment by linuxrider** [comment]
Unfortunately, this fix is only working while the svg is saved as "inkscape svg".
It does not work when saved as "normal svg".

**Comment by saraedum** [comment]
Yes, when there is no layer your code did not work for us.

**Comment by saraedum** [comment]
But sure, it's a bit unfortunate that we now expect the editor to be inkscape...

**Comment by saraedum** [comment]
I tried to improve our detection in #22.
