### ISSUE TITLE
property scaling_factors not working

### ISSUE THREAD

**Issue by FMMechem** [echemdb/svgdigitizer#166]
When using a scaling factor, the entered factor is not applied to the output data.

Data exported using `svgdigitizer cv --sampling-interval=0.001 filename.svg`
![WithoutScalingFactor](https://user-images.githubusercontent.com/123760456/215151322-fa60037f-3a4b-42e6-a096-c526bef5f672.svg)
![WithScalingFactor](https://user-images.githubusercontent.com/123760456/215151326-3fe2ff87-ec33-4f18-8c7a-202412a9ebe6.svg)

**Comment by DunklesArchipel** [comment]
Thank you for the hint. Indeed scaling factors only worked for `x` and `y` labels. This will be fixed in the next release.
