### ISSUE TITLE
The csv file is empty

### ISSUE THREAD

**Issue by GDufenshuoo** [echemdb/svgdigitizer#216]
When Follow the example in the documents, the csv file is empty. 
`<?xml version="1.0" encoding="utf-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:xlink="http://www.w3.org/1999/xlink" baseProfile="full" height="1418px" version="1.1" width="2126px">
  <defs/>
  <image height="1418px" sodipodi:insensitive="true" width="2126px" x="0" xlink:href="example_plot_paginate_p0.png" y="0"/>
</svg>
`

**Comment by DunklesArchipel** [comment]
Could you specify which SVG file was provided in the documentation you tried to digitize?

Your example seems to be the blank SVG without annotations, which only shows the linked figure.

The usage example is [this](https://echemdb.github.io/svgdigitizer/_downloads/f2fc828c330e883e90decece763656ec/looping.svg), which is based on [this figure](https://echemdb.github.io/svgdigitizer/_images/looping_p0.png).

**Comment by GDufenshuoo** [comment]
Thanks, I made some mistakes, now it works.

**Comment by DunklesArchipel** [comment]
Thanks for the feedback. I will try to improve the documentation in that respect. Have fun digitizing curves.
