### ISSUE TITLE
Let svgdigitizer create a simple csv file containing xy data

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#24]

**Comment by DunklesArchipel** [comment]
Instead, we implement a function in `csvcreator` that generates simple xy data csv file.

**Comment by saraedum** [comment]
I don't understand what you are proposing here. Could you elaborate?

**Comment by DunklesArchipel** [comment]
In my opinion the `svgdigitizer` should only return xy-data. Currently, this is `allfiles`.
The `csvcreator` should create csv files. The most simple case would be the creation of an x, y csv, based on the svg file.  This is the minimum requirement for any type of digitized data.

x|y
---|----
0|1
1| 2

Here x and y could also be replaced by some specific strings such as I, U or t, which can be given as input parameters to svgdigitizer. In 'svgdigitizer` this is required if you want the nice axis labels.

Besides the 'cvscreator' would contain some functions specifically designed to create csv files related to a specific data type, such as the data we have. These require for example the creation of a time axis that can be derived from the rate at which the data was acquired (given in the article).

In principle, the `svgdigitizer` is all you need to digitize your svg file. The `csvcreator` is only a quality of life improvement if you don't want to write your own function to create csv files.

**Comment by DunklesArchipel** [comment]
Solved in a different way.
* `svgplot` returns a `df` with x and y values. Conversion to csv is left to the user `df.to_csv('filename')`
* this works similarily for `cv`
