### ISSUE TITLE
top_level is never the SVG

### ISSUE THREAD

**Issue by saraedum** [echemdb/svgdigitizer#37]
`SVGPlot.labeled_paths()` does not seem to work for SVGs without layer groups. The `sorted_counts` does never seem to take the SVG itself into account contrary to what the comment there states:
```py
        # determine top level group (layer or svg) by counting groups
        # group with most subgroups is probably the relevant top level
        svg = self.doc.getElementsByTagName('svg')[0]
        group_counts = {}

        for group in svg.getElementsByTagName('g'):
            try:
                group_counts[group.parentNode] += 1
            except KeyError:
                group_counts[group.parentNode] = 1

        sorted_counts = sorted(group_counts.items(), key=lambda item: item[1],reverse=True)
        top_level = sorted_counts[0][0]
```

**Comment by linuxrider** [comment]
#39 adds a test which shows that it works with a svg without layer group.
The test svg is prepared by manually removing the layer tag from the file.
group_counts includes also svg if it is the parent of a group.

**Comment by saraedum** [comment]
Sorry, I missed the `.parentNode` in the code I quoted.
