### ISSUE TITLE
Add citation information

### ISSUE THREAD

**Issue by saraedum** [echemdb/svgdigitizer#55]
we should add a .zenodo.json to this repository so that it can be cited correctly via zenodo.

- [x] Add .zenodo.json
- [x] Finish docs #73 
- [x] Move yaml file into its own repo (https://github.com/echemdb/electrochemistry-metadata-schema)
- [x] Add rever scripts to release to PyPI (and zenodo.)

**Comment by DunklesArchipel** [comment]
- [ ] Finish Doku
- [ ] are we fine with the code
- [ ] Move yaml file into its own repo

**Comment by saraedum** [comment]
Finishing the docs is not really relevant for the zenodo part.
