### ISSUE TITLE
Remove automatic fixing of unit spellings

### ISSUE THREAD

**Issue by saraedum** [echemdb/svgdigitizer#95]
Eventually we won't be able to fix all unit spellings to make them match the astropy standard.

We should probably just drop this feature and instead produce a good error message when the unit cannot be understood, i.e., explain to the user in two sentences how units have to be spelled and link to a more detailed documentation on astropy.

**Comment by linuxrider** [comment]
#127

**Comment by linuxrider** [comment]
Units can now be written as e.g. "A cm-2", "A cm⁻²", "A / cm2" or "A / cm²" only relying on astropy.
